apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: {{BOOTSTRAP_TOKEN}}
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  name: {{HOSTNAME_OVERRIDE}}
  kubeletExtraArgs:
    provider-id: {{PROVIDER_ID}}
    hostname-override: {{HOSTNAME_OVERRIDE}}
    image-credential-provider-bin-dir: /usr/local/bin
    image-credential-provider-config: /etc/kubernetes/credential-provider.yaml
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: {{KUBERNETES_VERSION}}
apiServer:
  certSANs:
  - {{EXTRA_SANS}}
controllerManager:
  extraArgs:
networking:
  podSubnet: {{POD_CIDR}}